const { HttpAgent, Actor } = require('@dfinity/agent');
const fs = require('fs');
require('dotenv').config();

let _actor = null;

function createActor() {
    try {
        const agent = new HttpAgent({
            host: process.env.ICP_HOST || 'http://localhost:4943',
        });

        if ((process.env.ICP_HOST || '').includes('localhost')) {
            agent.fetchRootKey().catch(console.error);
        }

        // IDL factory would be generated by dfx build
        // For now, return a mock actor
        console.log('ICP Agent created for canister:', process.env.CANISTER_ID);
        return agent;
    } catch (err) {
        console.error('Failed to create ICP agent:', err.message);
        return null;
    }
}

function getActor() {
    if (!_actor) _actor = createActor();
    return _actor;
}

module.exports = { getActor };
