CREATE TABLE IF NOT EXISTS jobs (
    id                   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id           INT UNSIGNED NOT NULL,
    title                VARCHAR(255) NOT NULL,
    department           VARCHAR(100),
    description          LONGTEXT NOT NULL,
    responsibilities     JSON,
    required_skills      JSON,
    required_education   TEXT,
    required_certs       JSON,
    min_experience       INT DEFAULT 0,
    positions_count      INT DEFAULT 1,
    deadline             DATETIME NOT NULL,
    salary_min           DECIMAL(10,2),
    salary_max           DECIMAL(10,2),
    job_type             ENUM('REMOTE','ONSITE','HYBRID') DEFAULT 'ONSITE',
    employment_type      ENUM('FULL_TIME','PART_TIME','CONTRACT') DEFAULT 'FULL_TIME',
    location             VARCHAR(255),
    job_hash             CHAR(64),
    icp_confirmed        TINYINT(1) DEFAULT 0,
    marks_published      TINYINT(1) DEFAULT 0,
    status               ENUM('ACTIVE','SCREENING','EXAMINING','INTERVIEWING','COMPLETED') DEFAULT 'ACTIVE',
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FULLTEXT KEY ft_search (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
